---
s3_access_key: "{{ vault_s3_access_key }}"
s3_secret_key: "{{ vault_s3_secret_key }}"
dbsder_api_key: "{{ vault_dbsder_api_key }}"
dbsder_other_api_key: "{{ vault_dbsder_other_api_key }}"
dbsder_powerful_api_key: "{{ vault_dbsder_powerful_api_key }}"
doc_password: "{{ vault_doc_password }}"
minio_root_password: "{{ vault_minio_root_password }}"
av_pdf_path: "{{ vault_av_pdf_path }}"
oauth_client_secret: "{{ vault_oauth_client_secret}}"
commissioning_date: "2024-01-31"
av_node_name: "jud7vcorc901"
av_host_path: "/data/av"
authentication_key: "{{ vault_authentication_key }}"
hash_key: "{{ vault_hash_key }}"
auth_strategy: "oAuth2"
access_token_lifetime_in_seconds: "{{ vault_access_token_lifetime_in_seconds }}"
