---
ansible_user: iliasaaguida
ansible_python_interpreter: "/home/{{ ansible_user }}/ansible_venv/bin/python"

api_service: "api-service"
bucket_service: "bucket-service"
portalis_private_name: "pts.judilibre-prive.local"

s3_url: "http://bucket-service.juritj.svc.cluster.local:9000"
s3_region: "eu-west-paris-1"
s3_bucket_name: "portalis-collect-test-bucket"

use_auth: "oauth"
oauth_client_id: "portalis"
oauth_provider_url: "http://localhost:{{ api_port }}"
oauth_token_url: "{{ oauth_provider_url }}/token"

api_port: "3015"
nlp_pseudonymisation_api_url: "http://nlp-api-service.nlp.svc.cluster.local:8081"
dbsder_api_url: "http://{{ api_service }}.dbsder:3000"
authentication_id: "portalis"

node_env: "production"

normalization_batch_schedule: "* * * * *"
