---
- name: Creation de la ConfigMap de l'api
  k8s:
    apply: true
    state: present
    verify_ssl: true
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: api-config
        namespace: "{{ portalis_namespace }}"
        labels:
          app: "{{ portalis_application }}"
      data:
        NODE_ENV: "{{ node_env }}"
        DBSDER_API_URL: "{{ dbsder_api_url }}"
        PORT: "{{ api_port }}"
        USE_AUTH: "{{ use_auth }}"
        OAUTH_PROVIDER_URL: "{{ oauth_provider_url }}"
        OAUTH_CLIENT_ID: "{{ oauth_client_id }}"
        OAUTH_TOKEN_URL: "{{ oauth_token_url }}"
        NLP_PSEUDONYMISATION_API: "{{ nlp_pseudonymisation_api }}"
        AUTHENTICATION_ID: "{{ authentication_id }}"
        AUTH_STRATEGY: "{{ auth_strategy }}"
        ACCESS_TOKEN_LIFETIME_IN_SECONDS: "{{ access_token_lifetime_in_seconds }}"
...
