---
- name: Creation de la ConfigMap de l'api
  k8s:
    apply: true
    state: present
    verify_ssl: true
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: api-config
        namespace: "{{ portalis_namespace }}"
        labels:
          app: "{{ portalis_application }}"
      data:
        NODE_ENV: "{{ node_env }}"
        PORT: "{{ api_port }}"
        USE_AUTH: "{{ use_auth }}"
        AUTHENTICATION_ID: "{{ authentication_id }}"
        AUTHENTICATION_KEY: "{{ authentication_key }}"
        AUTH_STRATEGY: "{{ auth_strategy }}"
        ACCESS_TOKEN_LIFETIME_IN_SECONDS: "{{ access_token_lifetime_in_seconds }}"
        FILE_DB_URL: "{{ file_db_url }}"
...
