---
- name: Creation de la ConfigMap de l'api
  k8s:
    apply: true
    state: present
    verify_ssl: true
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: api-config
        namespace: "{{ portalis_namespace }}"
        labels:
          app: "{{ portalis_application }}"
      data:
        DOC_LOGIN: "{{ doc_login }}"
        DBSDER_API_URL: "{{ dbsder_api_url }}"
        NO_COLOR: "{{ no_color }}"
        PORT: "{{ api_port }}"
        USE_AUTH: "{{ use_auth }}"
        OAUTH_PROVIDER_URL: "{{ oauth_provider_url }}"
        OAUTH_CLIENT_ID: "{{ oauth_client_id }}"
        OAUTH_TOKEN_URL: "{{ oauth_token_url }}"
        PLAINTEXT_SOURCE: "{{ plaintext_source }}"
        NLP_PSEUDONYMISATION_API_URL: "{{ nlp_pseudonymisation_api_url }}"
        AUTHENTICATION_ID: "{{ authentication_id }}"
        AUTH_STRATEGY: "{{ auth_strategy }}"
...
