image: docker:$DOCKER_BUILD_VERSION_NEW
services:
  - docker:$DOCKER_BUILD_VERSION_NEW-dind

variables:
  HTTP_PROXY: $HTTP_PROXY_DEV
  HTTPS_PROXY: $HTTPS_PROXY_DEV
  PROJECT_VERSION: "1.0.0"

stages:
  - build
  - dev
  - preprod
  - prod

before_script:
  - echo "Logging in to Docker registry..."
  - echo $CI_JOB_TOKEN | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  - |
    if [ "$CI_DEFAULT_BRANCH" != "$CI_COMMIT_REF_NAME" ]; then
      export BRANCH_SUFFIX="${CI_COMMIT_REF_NAME}-"
    else
      export BRANCH_SUFFIX=""
    fi
  - export docker_image_dev="$CI_REGISTRY/$CI_PROJECT_PATH:${BRANCH_SUFFIX}latest-dev"
  - export docker_image="$CI_REGISTRY/$CI_PROJECT_PATH:${BRANCH_SUFFIX}latest"
  - export docker_image_version="$CI_REGISTRY/$CI_PROJECT_PATH:${BRANCH_SUFFIX}$PROJECT_VERSION"

build_dev:
  stage: build
  script:
    - docker build
        --build-arg http_proxy=$HTTP_PROXY
        --build-arg https_proxy=$HTTPS_PROXY
        -f dockerfile.dev
        -t $docker_image_dev .
    - docker push $docker_image_dev
  tags:
    - docker

build:
  stage: build
  script:
    - docker build
        --build-arg http_proxy=$HTTP_PROXY
        --build-arg https_proxy=$HTTPS_PROXY
        -f Dockerfile
        -t $docker_image .
    - docker push $docker_image
    - docker tag $docker_image $docker_image_version
    - docker push $docker_image_version
  tags:
    - docker

dev:
  stage: dev
  script:
    - docker pull $docker_image_dev
    - docker tag $docker_image_dev $CI_PROJECT_NAME-dev
  tags:
    - docker

preprod:
  stage: preprod
  script:
    - docker pull $docker_image
    - docker tag $docker_image $CI_PROJECT_NAME-preprod
  tags:
    - docker

prod:
  stage: prod
  script:
    - docker pull $docker_image
    - docker tag $docker_image $CI_PROJECT_NAME-prod
  tags:
    - docker
