image: docker:$DOCKER_BUILD_VERSION_NEW
services:
  - docker:$DOCKER_BUILD_VERSION_NEW-dind

variables:
  docker_image_dev: "$CI_REGISTRY/$CI_PROJECT_PATH:dev-$CI_COMMIT_SHORT_SHA"
  docker_image: "$CI_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_SHORT_SHA"
  HTTP_PROXY: $HTTP_PROXY_DEV
  HTTPS_PROXY: $HTTPS_PROXY_DEV

stages:
  - build
  - dev
  - preprod
  - prod

build_dev:
  stage: build
  script:
    - echo $CI_JOB_TOKEN | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - docker build
        --build-arg http_proxy=$HTTP_PROXY
        --build-arg https_proxy=$HTTPS_PROXY
        -f dockerfile.dev
        -t $docker_image_dev .
  tags:
    - docker

build:
  stage: build
  script:
    - echo $CI_JOB_TOKEN | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - docker build
        --build-arg http_proxy=$HTTP_PROXY
        --build-arg https_proxy=$HTTPS_PROXY
        -f Dockerfile
        -t $docker_image .
  tags:
    - docker

dev:
  stage: dev
  script:
    - docker pull $docker_image_dev
    - docker tag $docker_image_dev portalis-collect-dev
  tags:
    - docker

preprod:
  stage: preprod
  script:
    - docker pull $docker_image
    - docker tag $docker_image portalis-collect-preprod
  tags:
    - docker

prod:
  stage: prod
  script:
    - docker pull $docker_image
    - docker tag $docker_image portalis-collect-prod
  tags:
    - docker
