---
dev:
  children:
    externalproxy:
      hosts:
        externalproxyhost:
          ansible_host: 10.227.10.194
          ansible_user: "axelmarbois"

    proxy:
      hosts:
        proxy_host:
          ansible_host: 10.227.10.195

    k3s_master:
      hosts:
        k3s_master_host:
          ansible_host: 10.227.10.196

    gitlab:
      hosts:
        gitlabhost:
          ansible_user: "tomwilliams"
          ansible_host: 10.227.10.197

    gitlab_runner:
      hosts:
        gitlab_runner_host:
          ansible_user: "tomwilliams"
          ansible_host: 10.227.10.198
    
    db:
      hosts:
        dbhost:
          ansible_host: 10.227.10.199