---
prod:
  children:
    externalproxy:
      hosts:
        externalproxyhost:
          ansible_host: 10.227.11.201

    proxy:
      hosts:
        proxy_host:
          ansible_host: 10.227.11.200
          
    k3s_master:
      hosts:
        k3s_master_host:
          ansible_host: 10.227.11.202

    k3s_slaves:
      hosts:
        slave_one:
          ansible_host: 10.227.11.203
        slave_two:
          ansible_host: 10.227.11.204
        slave_three:
          ansible_host: 10.227.11.50
          
    db:
      hosts:
        dbhost:
          ansible_host: 10.227.11.205

    gitlab:
      hosts:
        gitlabhost:
          ansible_user: "tomwilliams"
          ansible_host: 10.227.10.197
