---
- name: Creation secrets api
  k8s:
    apply: true
    state: present
    verify_ssl: true
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: api-secret
        namespace: "{{ portalis_namespace }}"
        labels:
          app: "{{ portalis_application }}"
      type: Opaque
      data:
        DOC_PASSWORD: "{{ doc_password | b64encode }}"
        DBSDER_API_KEY: "{{ dbsder_api_key | b64encode }}"
        OAUTH_CLIENT_SECRET: "{{ oauth_client_secret | b64encode }}"
        AV_PDF_PATH: "{{ av_pdf_path | b64encode }}" 
        AUTHENTICATION_KEY: "{{ authentication_key | b64encode }}" 
        HASH_KEY: "{{ hash_key | b64encode }}" 
...
