---
- name: Creation api service
  k8s:
    apply: true
    state: present
    verify_ssl: true
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: "{{ api_service }}"
        namespace: "{{ portalis_namespace }}"
      spec:
        selector:
          app: "{{ app_id }}"
        ports:
          - name: api
            port: "{{ api_port }}"
            targetPort: "{{ api_port }}"
        type: ClusterIP

...
