---
- name: Create api Deployment
  k8s:
    apply: true
    state: present
    verify_ssl: true
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: "{{ app_id }}-deployment"
        namespace: "{{ portalis_namespace }}"
        labels:
          app:
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: "{{ app_id }}"
        template:
          metadata:
            labels:
              app: "{{ app_id }}"
          spec:
            containers:
              - name: "{{ app_id }}"
                image: "{{ portalis_image }}"
                ports:
                  - containerPort: 3015
                envFrom:
                  - configMapRef:
                      name: "api-config"
                  - secretRef:
                      name: "api-secret"
                  - configMapRef:
                      name: "s3-config"
                  - secretRef:
                      name: "s3-secret"
...
