---
- name: Creation de la ConfigMap de l'api
  k8s:
    apply: true
    state: present
    verify_ssl: true
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: api-config
        namespace: "{{ portalis_namespace }}"
        labels:
          app: "{{ portalis_application }}"
      data:
        ENV: "{{ env }}"
        PORT: "{{ api_port }}"
        AUTH_TYPE: "{{ auth_type }}"
        JWT_CLIENT_ID: "{{ jwt_client_id }}"
        JWT_ISSUER: "{{ jwt_issuer }}"
        JWT_ACCEPTED_ISSUERS: "{{ jwt_accepted_issuers }}"
        JWT_ALGORITHM: "{{ jwt_algorithm }}"
        JWT_EXPIRATION_SECONDS: "{{ jwt_expiration_seconds }}"
        S3_URL: "{{ s3_url }}"
        S3_REGION: "{{ s3_region }}"
        S3_BUCKET_NAME: "{{ s3_bucket_name }}"
...
