---
- name: Creation secrets api
  k8s:
    apply: true
    state: present
    verify_ssl: true
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: api-secret
        namespace: "{{ portalis_namespace }}"
        labels:
          app: "{{ portalis_application }}"
      type: Opaque
      data:
        JWT_CLIENT_SECRET: "{{ jwt_client_secret | b64encode }}"
        JWT_SECRET: "{{ jwt_secret | b64encode }}"
        S3_ACCESS_KEY: "{{ s3_access_key | b64encode }}"
        S3_SECRET_KEY: "{{ s3_secret_key | b64encode }}"
        FILE_DB_URL: "{{ file_db_url | b64encode }}"
...
