---
- name: Creation secrets api
  k8s:
    apply: true
    state: present
    verify_ssl: true
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: api-secret
        namespace: "{{ portalis_namespace }}"
        labels:
          app: "{{ portalis_application }}"
      type: Opaque
      data:
        AUTHENTICATION_KEY: "{{ authentication_key | b64encode }}"
        S3_ACCESS_KEY: "{{ s3_access_key | b64encode }}"
        S3_SECRET_KEY: "{{ s3_secret_key | b64encode }}"
        ACCESS_TOKEN_LIFETIME_IN_SECONDS: "{{ access_token_lifetime_in_seconds | b64encode }}"
        FILE_DB_URL: "{{ file_db_url | b64encode }}"
...
